name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What was expected to happen?
    validations:
      required: true   
  - type: textarea
    id: repro
    attributes:
      label: How can this bug be reproduced?
    validations:
      required: true  
  - type: input
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output into https://mclo.gs/ or alternitive
  - type: input
    id: loader-ver
    attributes:
      label: Fabric version
    validations:
      required: true   
  - type: input
    id: mod-ver
    attributes:
      label: Mod version
    validations:
      required: true
  - type: input
    id: mc-ver
    attributes:
      label: Minecraft version
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Anything else?
  - type: checkboxes
    id: version
    attributes:
      label: issue-checks
      description: To ensure the sanity of contributors please select the boxes that apply below
      options:
        - label: I have searched for similar issues
          required: true
        - label: I understand that my issue may be closed if inadequate info is provided
          required: true
        - label: I am using the latest version of the mod for my MC version
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/ArcticWarmth/DisableEnd/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct and have searched for any related issues
          required: true
