blank_issues_enabled: true
contact_links:
  - name: Support
    url: https://github.com/ArcticWarmth/DisableEnd/discussions
    about: Please ask and answer questions here insted of making an issue
  - name: Security issues
    url: mailto:security@arcticwarmth.net
    about: Please report security vulnerabilities to this email.
